# Generated by Django 6.0.2 on 2026-02-28 20:40

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('displayName', models.CharField(max_length=200)),
                ('serial', models.UUIDField(default=uuid.uuid4)),
                ('fqid', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
                ('visibility', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('contentType', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('serial', models.UUIDField(default=uuid.uuid4)),
                ('fqid', models.URLField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munch.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
                ('contentType', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('serial', models.UUIDField(default=uuid.uuid4)),
                ('fqid', models.URLField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munch.author')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munch.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='munch.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='munch.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
                ('serial', models.UUIDField(default=uuid.uuid4)),
                ('fqid', models.URLField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munch.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munch.entry')),
            ],
        ),
    ]
