# Generated by Django 6.0.2 on 2026-02-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, help_text='Tell us about yourself', null=True),
        ),
    ]
