# Generated by Django 6.0.1 on 2026-03-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('requesting', 'Requesting'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='requesting', max_length=25),
        ),
    ]
