# Generated by Django 6.0.3 on 2026-03-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_url', models.URLField()),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='munch.entry')),
            ],
            options={
                'unique_together': {('entry', 'inbox_url')},
            },
        ),
    ]
