# Generated by Django 6.0.1 on 2026-03-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0002_follow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
