# Generated by Django 6.0.1 on 2026-03-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0003_author_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='web',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/munch/api/'),
        ),
    ]
