# Generated by Django 6.0.1 on 2026-03-01 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0004_author_web_alter_author_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='object',
        ),
        migrations.AddField(
            model_name='like',
            name='object_url',
            field=models.URLField(default='', max_length=555),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('author', 'object_url'), name='unique_like_per_author'),
        ),
    ]
