# Generated by Django 6.0.1 on 2026-03-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0004_author_web_alter_author_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='markdownContent',
            field=models.TextField(blank=True),
        ),
    ]
