# Generated by Django 6.0.1 on 2026-03-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0005_entry_markdowncontent'),
        ('munch', '0005_remove_like_object_like_object_url_and_more'),
    ]

    operations = [
    ]
