# Generated by Django 6.0.1 on 2026-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0006_merge_20260311_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='github_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
