# Generated by Django 6.0.1 on 2026-03-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0007_entry_github_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
