# Generated by Django 6.0.1 on 2026-03-16 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0008_entry_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
