# Generated by Django 6.0.1 on 2026-03-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0010_alter_comment_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/api/'),
        ),
    ]
