# Generated by Django 6.0.1 on 2026-03-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0012_alter_author_options_alter_author_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=256)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
